Homework/aspnet/4
cleannetcode/LessonMonitor pull request #145
Opened 2021-10-15 23:48 UTC by Z1pP

2021-10-15 23:59 UTC, Z1pP commented
Выполнено ДЗ. Добавлена логика работы с GitHub

2021-10-18 20:13 UTC, pingvin1308 requested changes
В общем есть над чем поработать. Попробуй сделать фиксы того, что я отметил и подумай, может в коде что ещё не так сделано? :)

2021-10-18 20:13 UTC, pingvin1308 commented on LessonMonitor/LessonMonitor.API/Controllers/GitHubController.cs
> +        IGitHubService _githubService;
Не хватает модификатора доступа

2021-10-18 20:13 UTC, pingvin1308 commented on LessonMonitor/LessonMonitor.API/MyMiddlewareComponent.cs
> +            var loger = $"{request.Protocol},{request.Method}, {request.Scheme}, {request.QueryString.Value},{request.QueryString.Value}, {body}";
Пожалуй это не логер, а сообщение

2021-10-18 20:13 UTC, pingvin1308 commented on LessonMonitor/LessonMonitor.Core/IGitHubRepository.cs
> +        bool ChangeRepositoryName(string nameRep, string newName);
Не сокращай названия

2021-10-18 20:13 UTC, pingvin1308 commented on LessonMonitor/LessonMonitor.Core/UserCore.cs
> +    public class UserCore
Честно говоря суфикс Core не лучший выбор. Но да ладно :)

2021-10-18 20:13 UTC, pingvin1308 commented on LessonMonitor/LessonMonitoy.BusnessLogic/GitHubService.cs
> +        public bool ChangeRepositoryName(string nameRer, string newName)
Вот видишь до чего доводят сокращения :)
Поди теперь разберись то такое rer. А так была бы хотя бы понятная опечатка NameRerository. Правда тут можно просто написать name

2023-01-26 19:34 UTC, closed without merging