Homework/sql/2 (MSSQL - 2)
cleannetcode/LessonMonitor pull request #35
Opened 2021-04-28 12:26 UTC by Misha902

Не придумал где вставить связь 1к1
![image](https://user-images.githubusercontent.com/79799958/116402621-505df500-a835-11eb-95bd-4e2b236f228b.png)

2021-04-28 13:36 UTC, Jenausmax commented
Интересен вопрос отсутствия полей Id в Questions и  TimeCodes. Просто если вдруг нужно будет изменить базу и добавить связь для этих сущностей это будет сделать проблемно, имея например 10000 записей в таблице. Не добавлены Primary key в Topics и  MembersLessons. Не претендую на последнюю инстанцию...мое ИМХО.

2021-05-15 10:49 UTC, pingvin1308 requested changes

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	ID INT,
Следует сделать данный ID как Primary Key, либо сделать составной ключ из MemberID и LessonID

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	TimeCodes NVARCHAR(50)
Думаю можно убрать поле TimeCodes, так как судя по всему таймкоды в такой базе будут храниться в таблице TimeCodes.

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	LessonID INT NOT NULL,
Следует добавить уникальный идентификатор в таблицу TimeCodes. Подробности почему это важно будет на ближайшем занятии

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	UserName NVARCHAR(20) NOT NULL,
По ощущению в таблице не хватает ссылки на Member-а, который оставил таймкод

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	ID INT NOT NULL,
Идентификатор следует сделать Primary Key

2021-05-15 10:49 UTC, pingvin1308 commented on LessonMonitor/hw_2 createdb.sql
> +	MemberID INT NOT NULL,
Следует добавить уникальный идентификатор вопроса. Так как в последствии будут добавлены ответы на вопросы и без данных идентификаторов будет туго)

2021-05-15 11:31 UTC, pingvin1308 requested changes
Проверил, ожидаю правки :)

2021-05-21 08:12 UTC, Misha902 commented
Спасибо за отзыв, внес правки.
Долго не мог понять как правильно отправить коммит.
И походу отправил его не так как нужно

2021-05-26 21:21 UTC, pingvin1308 approved these changes
Принято :)
Только не забывай про такую штуку как IDENTITY(1,1). Ее довольно таки важно вставлять в идентификаторы, чтобы они генерировались и не приходилось их записывать в ручную

2022-08-08 08:52 UTC, closed without merging